apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
     cert-manager.io/cluster-issuer: letsencrypt-prod
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
     external-dns.alpha.kubernetes.io/hostname: tripqm.online
     external-dns.alpha.kubernetes.io/ttl: "120" #optional
spec:
  ingressClassName: nginx
  rules:
  - host: vprofile.tripqm.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              #name: https
              number: 8080
  tls:
  - hosts:
    - vprofile.tripqm.online
    secretName: vpro-tls