apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.3 # Replace with the desired Cert-Manager version
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: prometheus.enabled
          value: "false"
        - name: webhook.timeoutSeconds
          value: "4"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
